//API 1
GET http://localhost:3000/players/
###

//API 3
GET http://localhost:3000/players/1/
###

//API 2 
POST http://localhost:3000/players/
###

//API 4
PUT http://localhost:3000/players/7/
###

//API 5
DELETE http://localhost:3000/players/1/
###